import { Order, Budget, User } from './types';

// Usuários mock para demonstração
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Carlos Silva',
    email: 'carlos.silva@ultraacademia.com',
    role: 'operador',
    unidade: 'Unidade Centro',
  },
  {
    id: '2',
    name: 'Ana Paula Santos',
    email: 'ana.santos@ultraacademia.com',
    role: 'gerente',
    unidade: 'Unidade Centro',
  },
  {
    id: '3',
    name: 'Franklin Lima',
    email: 'franklin.lima@ultraacademia.com',
    role: 'diretor',
  },
  {
    id: '4',
    name: 'Juliana Costa',
    email: 'juliana.costa@ultraacademia.com',
    role: 'compras',
  },
  {
    id: '5',
    name: 'Fernando Lima',
    email: 'fernando.lima@ultraacademia.com',
    role: 'financeiro',
  },
  {
    id: '6',
    name: 'Mariana Oliveira',
    email: 'mariana.oliveira@ultraacademia.com',
    role: 'operador',
    unidade: 'Unidade Zona Sul',
  },
];

// Budgets por unidade
export const mockBudgets: Budget[] = [
  {
    unidadeId: 'centro',
    unidadeNome: 'Unidade Centro',
    mensal: 50000,
    consumido: 32500,
    disponivel: 17500,
    mes: 'Fevereiro/2026',
  },
  {
    unidadeId: 'zona-sul',
    unidadeNome: 'Unidade Zona Sul',
    mensal: 45000,
    consumido: 28000,
    disponivel: 17000,
    mes: 'Fevereiro/2026',
  },
  {
    unidadeId: 'zona-norte',
    unidadeNome: 'Unidade Zona Norte',
    mensal: 40000,
    consumido: 15000,
    disponivel: 25000,
    mes: 'Fevereiro/2026',
  },
  {
    unidadeId: 'zona-leste',
    unidadeNome: 'Unidade Zona Leste',
    mensal: 35000,
    consumido: 22000,
    disponivel: 13000,
    mes: 'Fevereiro/2026',
  },
];

// Pedidos de compra mock
export const mockOrders: Order[] = [
  {
    id: '1',
    numero: 'PED-2026-001',
    unidade: 'Unidade Centro',
    area: 'musculacao',
    tipo: 'equipamento',
    produto: 'Esteira Profissional TechnoGym',
    valorEstimado: 12000,
    valorFinal: 11500,
    justificativa: 'Substituição de equipamento com defeito na área de cardio',
    status: 'enviado_compras',
    solicitante: 'Carlos Silva',
    dataCriacao: '2026-02-01T10:30:00',
    dataAtualizacao: '2026-02-05T14:20:00',
    orcamentos: [
      {
        id: 'orc-1',
        fornecedor: 'FitEquip Comercial',
        valor: 11500,
        arquivo: 'orcamento-fitequip.pdf',
        dataEnvio: '2026-02-03T09:00:00',
      },
      {
        id: 'orc-2',
        fornecedor: 'Mega Sport Equipamentos',
        valor: 12200,
        arquivo: 'orcamento-megasport.pdf',
        dataEnvio: '2026-02-03T10:30:00',
      },
    ],
    historico: [
      {
        id: 'hist-1',
        data: '2026-02-01T10:30:00',
        acao: 'Pedido criado',
        usuario: 'Carlos Silva',
      },
      {
        id: 'hist-2',
        data: '2026-02-01T11:00:00',
        acao: 'Aprovado pelo Gerente',
        usuario: 'Ana Paula Santos',
      },
      {
        id: 'hist-3',
        data: '2026-02-03T15:00:00',
        acao: 'Orçamentos enviados',
        usuario: 'Carlos Silva',
      },
      {
        id: 'hist-4',
        data: '2026-02-04T10:00:00',
        acao: 'Orçamentos aprovados',
        usuario: 'Ana Paula Santos',
      },
      {
        id: 'hist-5',
        data: '2026-02-05T14:20:00',
        acao: 'Enviado para Compras',
        usuario: 'Sistema',
        detalhes: 'Notificação via Teams enviada',
      },
    ],
    aprovadores: {
      gerente: 'Ana Paula Santos',
    },
  },
  {
    id: '2',
    numero: 'PED-2026-002',
    unidade: 'Unidade Zona Sul',
    area: 'recepcao',
    tipo: 'material_operacional',
    produto: 'Sistema de Catraca Eletrônica',
    valorEstimado: 8500,
    justificativa: 'Modernização do sistema de controle de acesso',
    status: 'aguardando_aprovacao_diretor',
    solicitante: 'Mariana Oliveira',
    dataCriacao: '2026-02-04T09:15:00',
    dataAtualizacao: '2026-02-04T15:30:00',
    orcamentos: [],
    historico: [
      {
        id: 'hist-6',
        data: '2026-02-04T09:15:00',
        acao: 'Pedido criado',
        usuario: 'Mariana Oliveira',
      },
      {
        id: 'hist-7',
        data: '2026-02-04T15:30:00',
        acao: 'Aprovado pelo Gerente',
        usuario: 'Patricia Ramos',
        detalhes: 'Valor acima de R$ 5.000 requer aprovação do Diretor',
      },
    ],
    budgetExcedido: false,
  },
  {
    id: '3',
    numero: 'PED-2026-003',
    unidade: 'Unidade Centro',
    area: 'musculacao',
    tipo: 'suplemento',
    produto: 'Whey Protein 1kg - 50 unidades',
    valorEstimado: 3500,
    justificativa: 'Reposição de estoque para revenda',
    status: 'em_lancamento_orcamentos',
    solicitante: 'Carlos Silva',
    dataCriacao: '2026-02-05T08:00:00',
    dataAtualizacao: '2026-02-05T16:00:00',
    orcamentos: [],
    historico: [
      {
        id: 'hist-8',
        data: '2026-02-05T08:00:00',
        acao: 'Pedido criado',
        usuario: 'Carlos Silva',
      },
      {
        id: 'hist-9',
        data: '2026-02-05T16:00:00',
        acao: 'Aprovado pelo Gerente',
        usuario: 'Ana Paula Santos',
      },
    ],
  },
  {
    id: '4',
    numero: 'PED-2026-004',
    unidade: 'Unidade Zona Norte',
    area: 'manutencao',
    tipo: 'servico',
    produto: 'Manutenção preventiva ar-condicionado',
    valorEstimado: 1800,
    justificativa: 'Manutenção trimestral programada',
    status: 'orcamentos_enviados',
    solicitante: 'João Pereira',
    dataCriacao: '2026-02-03T14:00:00',
    dataAtualizacao: '2026-02-06T10:00:00',
    orcamentos: [
      {
        id: 'orc-3',
        fornecedor: 'ClimaTech Serviços',
        valor: 1650,
        arquivo: 'orcamento-climatech.pdf',
        dataEnvio: '2026-02-06T09:00:00',
      },
      {
        id: 'orc-4',
        fornecedor: 'RefriAr Manutenção',
        valor: 1750,
        arquivo: 'orcamento-refrigar.pdf',
        dataEnvio: '2026-02-06T09:30:00',
      },
      {
        id: 'orc-5',
        fornecedor: 'ArcondPlus',
        valor: 1900,
        arquivo: 'orcamento-arcondplus.pdf',
        dataEnvio: '2026-02-06T10:00:00',
      },
    ],
    historico: [
      {
        id: 'hist-10',
        data: '2026-02-03T14:00:00',
        acao: 'Pedido criado',
        usuario: 'João Pereira',
      },
      {
        id: 'hist-11',
        data: '2026-02-04T09:00:00',
        acao: 'Aprovado pelo Gerente',
        usuario: 'Ricardo Alves',
      },
      {
        id: 'hist-12',
        data: '2026-02-06T10:00:00',
        acao: 'Orçamentos enviados',
        usuario: 'João Pereira',
      },
    ],
  },
  {
    id: '5',
    numero: 'PED-2026-005',
    unidade: 'Unidade Centro',
    area: 'cardio',
    tipo: 'equipamento',
    produto: 'Bicicleta Ergométrica - 3 unidades',
    valorEstimado: 18000,
    justificativa: 'Expansão da área de cardio',
    status: 'aguardando_aprovacao_diretor',
    solicitante: 'Carlos Silva',
    dataCriacao: '2026-02-06T11:00:00',
    dataAtualizacao: '2026-02-06T14:00:00',
    orcamentos: [],
    historico: [
      {
        id: 'hist-13',
        data: '2026-02-06T11:00:00',
        acao: 'Pedido criado',
        usuario: 'Carlos Silva',
      },
      {
        id: 'hist-14',
        data: '2026-02-06T14:00:00',
        acao: 'Aprovado pelo Gerente',
        usuario: 'Ana Paula Santos',
        detalhes: 'Budget mensal da unidade será excedido - Requer aprovação do Diretor',
      },
    ],
    budgetExcedido: true,
  },
];
